### ISSUE TITLE
AttributeError: 'Quotation' object has no attribute 'customer'

### ISSUE THREAD

**Issue by khoran** [frappe/webshop#114]
When I click "Request for Quote" on a cart with some items, I get an "uncaught server exception: There was an error building this page". The stack trace is:
```
Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 20, in get_response
    response = renderer_instance.render()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
           ^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/utils.py", line 523, in cache_html_decorator
    html = func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 95, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 163, in update_context
    data = self.run_pymodule_method("get_context")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 223, in run_pymodule_method
    return method(self.context)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/webshop/webshop/templates/pages/order.py", line 43, in get_context
    "Customer", context.doc.customer, "loyalty_program"
                ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Quotation' object has no attribute 'customer'
```

I found the issue being discussed recently in this forum: https://discuss.frappe.io/t/attributeerror-quotation-object-has-no-attribute-customer-in-v14-3-1/97342/2

The fix suggested there is to change `context.doc.customer` to `context.doc.customer_name` on line 43 of webshopt/templates/pages/order.py. I also found I needed to make the same change on line 53. After making these changes everything has been working well for me. 
Thank you.

**Comment by GeoCommander** [comment]
![image](https://github.com/frappe/webshop/assets/71740113/9df1cada-1c2b-4a12-a4d8-e6803667f007)

I replicated this error and can conform it exists.

**Comment by 0xhaval** [comment]
Kindly, we need to solve this issue 
![image](https://github.com/frappe/webshop/assets/35600969/56bf2478-0285-4996-a9a4-236352c26857)

**Comment by 0xCCY** [comment]
Bump for attention, this is a critical bug that blocks quotation workflow.

**Comment by Nihantra-Patel** [comment]
PR already raised: https://github.com/frappe/webshop/pull/139

**Comment by Rebaz-balisani** [comment]
I updated my erpnext today and yet the issue not resolved
![image](https://github.com/frappe/webshop/assets/84542451/4b825bf9-6e0c-4cb9-b329-b6de756b6f68)

**Comment by clevermind-me** [comment]
Hi! @Nihantra-Patel 
I have the same problem in Webshop: v0.0.1 (develop) when from Cart press button "Request for Quote"
Please tell what is the way to fix it?

<img width="658" alt="Image" src="https://github.com/user-attachments/assets/1371d6f4-c1a1-452c-aa36-db8cb2cc8cb4" />
