### ISSUE TITLE
Permission Issue on completing the sale

### ISSUE THREAD

**Issue by ravi854** [frappe/webshop#195]
On clicking pay Pay button on website to complete the sale,
getting permission error "You do not have enough permissions to complete the action

ERPNext: v15.32.1 (version-15)
Frappe Framework: v15.37.0 (version-15)
Frappe Whatsapp: vv1.0.7 (master)
Frappe HR: v15.25.2 (version-15)
Payment Gateway Payfast: v0.0.6 (master)
Webshop: v0.0.1 (version-15)

https://github.com/user-attachments/assets/79e67279-f63e-48e3-bb95-2fc17d8f2ace

**Comment by Nihantra-Patel** [comment]
Add access in "Customer Portal Users" in customer master, please check it.

https://discuss.frappe.io/t/sales-invoice-list-display-but-when-i-choose-one-of-this-it-give-me-not-permitted/124631/2?u=ncp

https://discuss.frappe.io/t/nothing-to-show-in-request-for-quotation-portal/120552/3?u=ncp
