### ISSUE TITLE
Page Not Found:- navigating a product listing page url from one browser to another

### ISSUE THREAD

**Issue by sharif-dotcom** [frappe/webshop#200]
When one creates a stock item group and then see on a website  it will render the product listing page for the browser, transferring that page  href that is :- https://site_name/products too another browser it shows there's no page found.
Getting back to the first browser and you refresh, its also shows the no such page until you navigate and make a change the value in the route field to be used and then you access the page

**Comment by umairsy** [comment]
Edit: @Nihantra-Patel  fixed this issue

I could replicate it. The Item Group page did not load at all if I was not signed in as a user. If I accessed it as a non-user, the page didn't load at all. If I was logged, it loaded the page for Item group fine.

Also, options like Add to Quote and Add to Cart won't show unless user is logged in.
