### ISSUE TITLE
The customer is not found

### ISSUE THREAD

**Issue by phalouvas** [frappe/webshop#44]
After login a customer doctype is created with user full name. After login code crashes on file webshop/webshop/utils/portal.py line 35.

I suggest you change this from 
`party = frappe.get_doc(doc_type, user) or create_customer_or_supplier()`
to 
`party = create_customer_or_supplier()`

and problem will be solved.

**Comment by donnieferdian** [comment]
same problem
<img width="563" alt="Screenshot 2024-01-15 at 02 47 49" src="https://github.com/frappe/webshop/assets/109821040/69587e57-06a0-449f-9126-a17f6d34899d">

@ankush
