### ISSUE TITLE
Navigation Bar Link Problem (404 - Page Not Found)

### ISSUE THREAD

**Issue by donnieferdian** [frappe/webshop#56]
Hi @ankush ,
I have a problem with the website navigation bar.
which I configured according to the route link, 
when I click some link the result is 404. sometimes work, but after 5-10 minute the result back to 404.
<img width="1055" alt="Screenshot 2024-01-15 at 03 03 58" src="https://github.com/frappe/webshop/assets/109821040/822b58fa-e617-4b96-a080-5f54a1a5f240">

<br>
<br>

<img width="1366" alt="Screenshot 2024-01-15 at 03 05 19" src="https://github.com/frappe/webshop/assets/109821040/63c53a16-a87c-4fe6-ad92-aea2398e1d20">

I have cleared the cache on the browser and on the terminal server, but still the result is the same.

here's the video
https://youtu.be/ByvZKYYYDjo

**Comment by donnieferdian** [comment]
update :
maybe i found the problem,
guest cant view web item group.
user with role customer cant view web item group.

and if guest/customer access the item group on website it will be show 404,..
if the error has occurred, users with administrator level will also get the same error

hope it can be fix soon....🙏🏻

**Comment by SaQDS** [comment]
I have same issue; web item groups are working with admin user but as soon as guest user loads such page it turns to 404 and admin user also sees 404 afterwords.

**Comment by donnieferdian** [comment]
> I have same issue; web item groups are working with admin user but as soon as guest user loads such page it turns to 404 and admin user also sees 404 afterwords.

@SaQDS please use the latest version,..

**Comment by SaQDS** [comment]
> > I have same issue; web item groups are working with admin user but as soon as guest user loads such page it turns to 404 and admin user also sees 404 afterwords.
> 
> @SaQDS please use the latest version,..

Nop, this won't help for me. I updated to latest versions for all apps, but issue still there. 
Do you have any special ways to update? 
thanks

**Comment by donnieferdian** [comment]
> > > I have same issue; web item groups are working with admin user but as soon as guest user loads such page it turns to 404 and admin user also sees 404 afterwords.
> > 
> > 
> > @SaQDS please use the latest version,..
> 
> Nop, this won't help for me. I updated to latest versions for all apps, but issue still there. Do you have any special ways to update? thanks

what version you used right now ??

see this PR [#40881](https://github.com/frappe/erpnext/pull/40881)

**Comment by SaQDS** [comment]
> > > > I have same issue; web item groups are working with admin user but as soon as guest user loads such page it turns to 404 and admin user also sees 404 afterwords.
> > > 
> > > 
> > > @SaQDS please use the latest version,..
> > 
> > 
> > Nop, this won't help for me. I updated to latest versions for all apps, but issue still there. Do you have any special ways to update? thanks
> 
> what version you used right now ??
> 
> see this PR [#40881](https://github.com/frappe/erpnext/pull/40881)

Here is the version: 

Installed Apps
ERPNext: v15.25.0 (version-15)
Frappe Framework: v15.28.0 (version-15)
Payments: v0.0.1 (develop)
Webshop: v0.0.1 (version-15)
